### This code generated by Deepseek

import os
import json
import base64
import boto3
from datetime import datetime

s3 = boto3.client('s3')

def lambda_handler(event, context):
    try:
        # Parse the incoming event
        body = json.loads(event['body'])
        file_content = base64.b64decode(body['file'])
        
        # Get filename from headers or generate one
        filename = event['headers'].get('filename') or f"upload_{datetime.now().strftime('%Y%m%d%H%M%S')}"
        
        # Determine file extension based on content type or filename
        if 'content-type' in event['headers']:
            content_type = event['headers']['content-type'].lower()
            if 'csv' in content_type:
                extension = '.csv'
            elif 'excel' in content_type or 'xls' in content_type:
                extension = '.xlsx' if 'openxml' in content_type else '.xls'
            else:
                extension = os.path.splitext(filename)[1] or '.bin'
        else:
            extension = os.path.splitext(filename)[1] or '.bin'
        
        # Clean filename and add extension if not present
        clean_filename = os.path.basename(filename).replace(' ', '_')
        if not clean_filename.lower().endswith(('.csv', '.xls', '.xlsx')):
            clean_filename += extension
        
        # Upload to S3
        s3_key = f"uploads/{clean_filename}"
        s3.put_object(
            Bucket=os.environ['S3_BUCKET'],
            Key=s3_key,
            Body=file_content,
            ContentType=event['headers'].get('content-type', 'application/octet-stream')
        )
        
        return {
            'statusCode': 200,
            'headers': {
                'Access-Control-Allow-Origin': '*',
                'Access-Control-Allow-Credentials': True,
                "Access-Control-Allow-Headers": "Content-Type, Authorization",
                    "Access-Control-Allow-Methods": "OPTIONS,POST"
            },
            'body': json.dumps({
                'message': 'File uploaded successfully',
                'filename': clean_filename,
                's3_key': s3_key
            })
        }
        
    except Exception as e:
        print(f"Error: {str(e)}")
        return {
            'statusCode': 500,
            'headers': {
                'Access-Control-Allow-Origin': '*',
                'Access-Control-Allow-Credentials': True
            },
            'body': json.dumps({
                'error': 'Failed to upload file',
                'details': str(e)
            })
        }